### ISSUE TITLE
Action failed: c:quickActionsEverywhere$controller$flowStatusChange [Cannot read property 'length' of undefined]

### ISSUE THREAD

**Issue by jbunford** [jmdohn/Quick-Actions-Everywhere#10]
I've used QAE in one area successfully linking to a flow.
I replicated my setup but with another flow and get the following error:
`This page has an error. You might just need to refresh it. Action failed: c:quickActionsEverywhere$controller$flowStatusChange [Cannot read property 'length' of undefined] Callback failed: serviceComponent://ui.interaction.runtime.components.controllers.FlowRuntimeController/ACTION$runInterview Failing descriptor: {c:quickActionsEverywhere$controller$flowStatusChange}`

**Comment by jmdohn** [comment]
Can you post the parameters? Have you also defined the recordId input and output variable?

**Comment by jbunford** [comment]
Hi Jeremiah, my mistake - I had forgotten to set the flow variable to output.
